import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import HomeSidebar from "./components/home-sidebar/HomeSidebar";
import HomeHeader from "./components/home-header/HomeHeader";
import { ModelSelectionStoreProvider } from "@/providers/model-selection-store-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/providers/auth-provider";
import AuthGuard from "@/components/AuthGuard";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          attribute={"class"}
          defaultTheme="dark"
        >
          <TooltipProvider>
            <AuthProvider>
              <AuthGuard>
                <SidebarProvider>
                  <HomeSidebar />
                  <ModelSelectionStoreProvider>
                    <main className="w-full">
                      <HomeHeader />
                      {children}
                    </main>
                    <Toaster richColors />
                  </ModelSelectionStoreProvider>
                </SidebarProvider>
              </AuthGuard>
            </AuthProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
